version: '3.8'
services:
  db:
    image: presto-db
    container_name: presto-db
    build: db
    environment:
      MYSQL_ROOT_PASSWORD: presto-password
      TZ: "UTC"
    ports:
      - "127.0.0.1:3306:3306"