version: '3.8'
services:
  db:
    image: presto-db
    container_name: presto-db
    build: db
    environment:
      MYSQL_ROOT_PASSWORD: presto-password
      TZ: "UTC"
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD
  api-server:
    image: presto-backend
    container_name: presto-backend
    build: .
    env_file: .env.docker
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      db:
        condition: service_healthy